#应用服务端口号本地用
server:
  port: 38443
spring:
  #profiles:
  config:
    active:
      on-profile:
        - dev
    include:
      - ding-pan-groups
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 100MB
      #总文件大小
      max-request-size: 100MB
  redis:
    #Redis服务器数据库
    database: 8
    #Redis服务器地址
    host: 150.158.130.169
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: '123456'
    #连接超时时间（毫秒）
    timeout: 30000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

ding-pan:
  urlConstant:
    #获取access_token url
    GET_ACCESS_TOKEN_URL: https://oapi.dingtalk.com/gettoken
    #通过免登授权码获取用户信息 url
    GET_USER_INFO_URL: https://oapi.dingtalk.com/topapi/v2/user/getuserinfo
    #通过免登授权码获取用户信息 url
    USER_GET_URL: https://oapi.dingtalk.com/topapi/v2/user/get
    #获取用户userid下的钉盘空间id
    GET_SPACE_ID_URL: https://oapi.dingtalk.com/topapi/processinstance/cspace/info

  windowPath: D://文件服务器//测试//ccc.pdf
  linuxPath: //home/paas//ccc.pdf

ding-pan-groups:
  preferRegion: ZHANGJIAKOU
  groupConstants:
    #    - groupTAG: RZGTEST
    #      corpId: ding7c130964a07b3c11a39a90f97fcb1e09
    #        #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppKey
    #      APP_KEY: dingvqeswc06gq6zm7gd
    #        #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppSecret
    #      APP_SECRET: HiIakE4Annig3ULFrrhaiqHZCXS6_xM4k97CVhIC467xLJ9V226e2BYcE7gNJblD

    #    - groupTAG: lmbs
    #      corpId: ding7c130964a07b3c11a39a90f97fcb1e09
    #      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppKey
    #      APP_KEY: dinge8fnetcnfc0otyah
    #      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppSecret
    #      APP_SECRET: QmlUvkob3byeIoCzzg1qsIpAEcqK9opshmvXd4qqIK3V6ea0k4PsRMR20tdvLhm1
    #
    #      日照港技术创新中心
    - groupTAG: jscxzx
      corpId: dingb8c1879ddc0d5c84ee0f45d8e4f7c288
      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppKey
      APP_KEY: ding0kwsexk8nkkwssho
      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppSecret
      APP_SECRET: t-yvBwQS5IccJj_26LEzdiEBQg5D7q0_1rzLJZsT_OEeTlugK3f3GHgZGUq53WgQ

    #      日照港集团有限公司
    - groupTAG: rzgjt
      corpId: ding6fbc1d3b2a6fbbd935c2f4657eb6378f
      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppKey
      APP_KEY: dingfqxb70u8gny10jhs
      #开发者后台->应用开发-企业内部应用->选择您的小程序->凭证与基础信息->AppSecret
      APP_SECRET: fe7RUVyYFIJDhnNHEY6Me-n3YvrxmNBr-waxg7WFPHLQoapQ8sX406SjXwQyEyOx