spring:
  datasource:
    clickhouse:
      address: jdbc:clickhouse://cc-bp1k371ufr3u1z397o.ads.rds.aliyuncs.com:8123
      username: zhangertong
      password: 1qaz@WSX
      db: PS
      socketTimeout: 600000
      mapper-locations: classpath*:login/mapper/**/*.xml,classpath*:trustsighting/mapper/**/*.xml
      #      password: ENC(1c1c35eb7e0e59aacd09cfe556832497b756a2d9a60d2ed2bcb24393b462fdefc3e294225d9d1279046a61ba8eb85fe5)
#    sz:
#      url: jdbc:postgresql://100.93.16.190:5432/dev-sz-tenant?currentSchema=public&allowMultiQueries=true&useSSL=false
#      driverClassName: org.postgresql.Driver
#      username: dev-sz-tenant
#      password: ENC(1c1c35eb7e0e59aacd09cfe556832497b756a2d9a60d2ed2bcb24393b462fdefc3e294225d9d1279046a61ba8eb85fe5)
#      mapper-locations: classpath*:trustsighting/mapper/**/*.xml

server:
  address: localhost
  port: 8899